### ISSUE TITLE
An error occurred when exporting the Ominous Banner.

### ISSUE THREAD

**Issue by EvanHsieh0415** [CyclopsMC/IconExporter#21]
#### Issue type:

- :bug: Bug 

____

#### Short description:

When I try to export all the icons, there is one and only one item that is displayed incorrectly, and that item is ominous_banner.

#### Steps to reproduce the problem:

1. Use the command `/iconexporter export`

#### Expected behaviour:

Export is complete and error free

____

#### Versions:

- This mod: `1.2.4`
- Minecraft: `1.20.1`
- Forge: `47.1.47`

#### Log file:

https://mclo.gs/1lxVuAL

<details>

<summary> Related Log Segments </summary>

```java
[18:24:21] [Render thread/ERROR] [iconexporter/]: Error while writing the PNG image for key minecraft__white_banner__{BlockEntityTag__{Patterns__[{Color__9,Pattern__'mr'},{Color__8,Pattern__'bs'},{Color__7,Pattern__'cs'},{Color__8,Pattern__'bo'},{Color__15,Pattern__'ms'},{Color__8,Pattern__'hh'},{Color__8,Pattern__'mc'},{Color__15,Pattern__'bo'}],id__'minecraft__banner'},HideFlags__32,display__{Name__'{'color'__'gold','translate'__'block.minecraft.ominous_banner'}'}}
[18:24:21] [Render thread/INFO] [minecraft/ChatComponent]: [System] [CHAT] Error while exporting
java.io.IOException: 參數錯誤。
	at java.base/java.io.WinNTFileSystem.canonicalize0(Native Method)
	at java.base/java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:462)
	at java.base/java.io.File.getCanonicalPath(File.java:626)
	at java.base/java.io.File.getCanonicalFile(File.java:651)
	at TRANSFORMER/iconexporter@1.2.4/org.cyclops.iconexporter.client.gui.ImageExportUtil.exportImageFromScreenshot(ImageExportUtil.java:48)
	at TRANSFORMER/iconexporter@1.2.4/org.cyclops.iconexporter.client.gui.ScreenIconExporter.lambda$createExportTasks$1(ScreenIconExporter.java:120)
	at TRANSFORMER/iconexporter@1.2.4/org.cyclops.iconexporter.client.gui.ScreenIconExporter.m_88315_(ScreenIconExporter.java:62)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109)
	at TRANSFORMER/forge@47.1.47/net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:427)
	at TRANSFORMER/forge@47.1.47/net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:420)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.47/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.47/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.47/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:58)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```

</details>

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
You'll have to set `fileNameHashTag` to `true` in your config.

**Comment by EvanHsieh0415** [comment]
> You'll have to set `fileNameHashTag` to `true` in your config.

Same problem...
![in game](https://github.com/CyclopsMC/IconExporter/assets/74277414/dc24830d-7e2a-47ef-8d34-e149fb313d4e)
![log](https://github.com/CyclopsMC/IconExporter/assets/74277414/1a9146c8-3c79-4899-a102-89ec60f2b464)

**Comment by rubensworks** [comment]
It looks like you've updated the config from the command line? Could you try restarting your game with the updated config?

**Comment by EvanHsieh0415** [comment]
> It looks like you've updated the config from the command line? Could you try restarting your game with the updated config?

it work and exported successful, thx!
