### ISSUE TITLE
Mod stops working with error when rendering

### ISSUE THREAD

**Issue by BedrockLegends** [CyclopsMC/IconExporter#3]
#### Issue type:

- :bug: Bug

____

#### Short description:
[14:45:02] [Client thread/INFO] [journeymap]: JourneyMap: Press [J]
[14:45:04] [Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 3043ms behind, skipping 60 tick(s)
[14:45:04] [Server thread/INFO] [net.minecraft.server.integrated.IntegratedServer]: Saving and pausing game...
[14:45:04] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'New World'/overworld
[14:45:05] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'New World'/Storage Cell
[14:45:12] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] Error while exporting
[14:45:12] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: java.io.IOException: The parameter is incorrect
[14:45:12] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at java.io.WinNTFileSystem.canonicalize0(Native Method)
[14:45:12] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at java.io.WinNTFileSystem.canonicalize(Unknown Source)
[14:45:12] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at java.io.File.getCanonicalPath(Unknown Source)
[14:45:12] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at java.io.File.getCanonicalFile(Unknown Source)
[14:45:12] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at org.cyclops.iconexporter.client.gui.ImageExportUtil.exportImageFromScreenshot(ImageExportUtil.java:46)
[14:45:12] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at org.cyclops.iconexporter.client.gui.GuiIconExporter.lambda$createExportTasks$0(GuiIconExporter.java:78)
[14:45:12] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at org.cyclops.iconexporter.client.gui.GuiIconExporter.func_73863_a(GuiIconExporter.java:48)
[14:45:12] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
[14:45:12] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
[14:45:12] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
[14:45:12] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3942)
[14:45:12] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[14:45:12] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:45:12] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[14:45:12] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:45:12] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[14:45:12] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[14:45:12] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[14:45:24] [Server thread/INFO] [net.minecraft.server.integrated.IntegratedServer]: Saving and pausing game...
[14:45:25] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'New World'/overworld
[14:45:25] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'New World'/Storage Cell
[14:45:32] [Client thread/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] Error while exporting
[14:45:32] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: java.io.IOException: The parameter is incorrect
[14:45:32] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at java.io.WinNTFileSystem.canonicalize0(Native Method)
[14:45:32] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at java.io.WinNTFileSystem.canonicalize(Unknown Source)
[14:45:32] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at java.io.File.getCanonicalPath(Unknown Source)
[14:45:32] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at java.io.File.getCanonicalFile(Unknown Source)
[14:45:32] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at org.cyclops.iconexporter.client.gui.ImageExportUtil.exportImageFromScreenshot(ImageExportUtil.java:46)
[14:45:32] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at org.cyclops.iconexporter.client.gui.GuiIconExporter.lambda$createExportTasks$0(GuiIconExporter.java:78)
[14:45:32] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at org.cyclops.iconexporter.client.gui.GuiIconExporter.func_73863_a(GuiIconExporter.java:48)
[14:45:32] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
[14:45:32] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
[14:45:32] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
[14:45:32] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3942)
[14:45:32] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at net.minecraft.client.main.Main.main(SourceFile:123)
[14:45:32] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:45:32] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[14:45:32] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:45:32] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[14:45:32] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[14:45:32] [Client thread/INFO] [STDERR]: [org.cyclops.iconexporter.client.gui.GuiIconExporter:func_73863_a:51]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[14:45:59] [Server thread/INFO] [net.minecraft.server.integrated.IntegratedServer]: Saving and pausing game...
[14:45:59] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'New World'/overworld
[14:45:59] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving chunks for level 'New World'/Storage Cell

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: IconExporter-1.12.2-1.0.0
- Minecraft: 1.12.2
- Forge:  14.23.5.2838

#### Log file:
[latest.log](https://github.com/CyclopsMC/IconExporter/files/3403596/latest.log)

**Comment by rubensworks** [comment]
From the stacktrace, I was not able to determine the cause of the problem.

Could you try out the latest dev build and share your full Forge log file after the problem occurred?

**Comment by BedrockLegends** [comment]
latest dev build?

**Comment by rubensworks** [comment]
See the maven link on the README of this repo.
